services:
  smit-main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: smit-main-app
    ports:
      - "${API_PORT}:8000"
    command: >
      bash -c "alembic upgrade head && gunicorn app.app.api.app:create_app --workers 8
      --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    # command: >
    #   bash -c "alembic upgrade head &&
    #   uvicorn --factory app.app.api.app:create_app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env
    volumes:
      - ../.:/app/
    depends_on:
      postgres:
        condition: service_healthy

networks:
  smit_network:
    driver: bridge
