"""Initial migration

Revision ID: 33f83d38583c
Revises: 
Create Date: 2024-11-18 23:26:16.144005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33f83d38583c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariff',
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('cargo_type', sa.String(), nullable=True),
    sa.Column('oid', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('oid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tariff')
    # ### end Alembic commands ###
